// Copyright (C) 2023 The BobUI Company Ltd.
// SPDX-License-Identifier: LicenseRef-BobUI-Commercial OR BSD-3-Clause

// This file was generated by the bobui_add_resources command.

#include <BobUICore/bobuisymbolmacros.h>

BOBUI_DECLARE_EXTERN_RESOURCE(@RESOURCE_NAME@)

namespace {
    struct resourceReferenceKeeper {
        resourceReferenceKeeper() { BOBUI_KEEP_RESOURCE(@RESOURCE_NAME@) }
    } resourceReferenceKeeperInstance;
}
