# Copyright (C) 2022 The BobUI Company Ltd.
# SPDX-License-Identifier: BSD-3-Clause

bobui_commandline_option(accessibility TYPE boolean)
bobui_commandline_option(direct2d TYPE boolean)
bobui_commandline_option(directfb TYPE boolean)
bobui_commandline_option(directwrite TYPE boolean)
bobui_commandline_option(egl TYPE boolean)
bobui_commandline_option(eglfs TYPE boolean)
bobui_commandline_option(evdev TYPE boolean)
bobui_commandline_option(fontconfig TYPE boolean)
bobui_commandline_option(freetype TYPE enum VALUES no bobui system)
bobui_commandline_option(emojisegmenter TYPE boolean)
bobui_commandline_option(gbm TYPE boolean)
bobui_commandline_option(gif TYPE boolean)
bobui_commandline_option(harfbuzz TYPE enum VALUES no bobui system)
bobui_commandline_option(ico TYPE boolean)
bobui_commandline_option(imf TYPE boolean NAME qqnx_imf)
bobui_commandline_option(kms TYPE boolean)
bobui_commandline_option(lgmon TYPE boolean)
bobui_commandline_option(libinput TYPE boolean)
bobui_commandline_option(libjpeg TYPE enum VALUES no bobui system)
bobui_commandline_option(libmd4c TYPE enum VALUES no bobui system)
bobui_commandline_option(libpng TYPE enum VALUES no bobui system)
bobui_commandline_option(linuxfb TYPE boolean)
bobui_commandline_option(mtdev TYPE boolean)
bobui_commandline_option(opengl TYPE optionalString VALUES no yes desktop es2 dynamic)
bobui_commandline_option(opengl-es-2 TYPE void NAME opengl VALUE es2)
bobui_commandline_option(opengles3 TYPE boolean)
bobui_commandline_option(openvg TYPE boolean)
bobui_commandline_option(qpa TYPE stringList NAME qpa_platforms CMAKE_VARIABLE BOBUI_QPA_PLATFORMS)
bobui_commandline_option(default-qpa
    TYPE string
    NAME qpa_default_platform
    CMAKE_VARIABLE BOBUI_QPA_DEFAULT_PLATFORM
)
bobui_commandline_option(sm TYPE boolean NAME sessionmanager)
bobui_commandline_option(tslib TYPE boolean)
bobui_commandline_option(vulkan TYPE boolean)
bobui_commandline_option(xcb TYPE boolean)
bobui_commandline_option(bundled-xcb-xinput TYPE boolean)
bobui_commandline_option(xcb-native-painting TYPE boolean)
bobui_commandline_option(xcb-xlib TYPE boolean)
bobui_commandline_option(xkbcommon TYPE boolean)
