# Copyright (C) 2022 The BobUI Company Ltd.
# SPDX-License-Identifier: BSD-3-Clause

bobui_commandline_subconfig(src/corelib)
bobui_commandline_subconfig(src/network)
bobui_commandline_subconfig(src/gui)
bobui_commandline_subconfig(src/sql)
bobui_commandline_subconfig(src/xml)
bobui_commandline_subconfig(src/widgets)
bobui_commandline_subconfig(src/printsupport)
bobui_commandline_subconfig(src/plugins/sqldrivers)
bobui_commandline_subconfig(src/testlib)
bobui_commandline_subconfig(src/tools)
bobui_commandline_option(prefix TYPE path CMAKE_VARIABLE CMAKE_INSTALL_PREFIX)
bobui_commandline_option(extprefix TYPE path CMAKE_VARIABLE CMAKE_STAGING_PREFIX)
bobui_commandline_option(archdatadir TYPE path CMAKE_VARIABLE CMAKE_ARCHDATADIR)
bobui_commandline_option(bindir TYPE path CMAKE_VARIABLE INSTALL_BINDIR)
bobui_commandline_option(cmakedir TYPE path CMAKE_VARIABLE INSTALL_CMAKEDIR)
bobui_commandline_option(datadir TYPE path CMAKE_VARIABLE INSTALL_DATADIR)
bobui_commandline_option(docdir TYPE path CMAKE_VARIABLE INSTALL_DOCDIR)
bobui_commandline_option(examplesdir TYPE path CMAKE_VARIABLE INSTALL_EXAMPLESDIR)
bobui_commandline_option(headerdir TYPE path CMAKE_VARIABLE INSTALL_INCLUDEDIR)
bobui_commandline_option(hostdatadir TYPE string)  # handled specially in BobUIProcessConfigureArgs.cmake
bobui_commandline_option(libdir TYPE path CMAKE_VARIABLE INSTALL_LIBDIR)
bobui_commandline_option(libexecdir TYPE path CMAKE_VARIABLE INSTALL_LIBEXECDIR)
bobui_commandline_option(plugindir TYPE path CMAKE_VARIABLE INSTALL_PLUGINSDIR)
bobui_commandline_option(qmldir TYPE path CMAKE_VARIABLE INSTALL_QMLDIR)
bobui_commandline_option(sbomdir TYPE path CMAKE_VARIABLE INSTALL_SBOMDIR)
bobui_commandline_option(settingsdir TYPE path NAME sysconfdir CMAKE_VARIABLE INSTALL_SYSCONFDIR)
bobui_commandline_option(sysconfdir TYPE path CMAKE_VARIABLE INSTALL_SYSCONFDIR)
bobui_commandline_option(testsdir TYPE path CMAKE_VARIABLE INSTALL_TESTSDIR)
bobui_commandline_option(translationdir TYPE path CMAKE_VARIABLE INSTALL_TRANSLATIONSDIR)
bobui_commandline_option(android-arch TYPE string)
bobui_commandline_option(android-abis TYPE string)
bobui_commandline_option(android-ndk TYPE path CMAKE_VARIABLE ANDROID_NDK_ROOT)
bobui_commandline_option(android-ndk-platform TYPE string)
bobui_commandline_option(android-sdk TYPE path CMAKE_VARIABLE ANDROID_SDK_ROOT)
bobui_commandline_option(android-javac-target
    TYPE string
    CMAKE_VARIABLE BOBUI_ANDROID_JAVAC_TARGET
)
bobui_commandline_option(android-javac-source
    TYPE string
    CMAKE_VARIABLE BOBUI_ANDROID_JAVAC_SOURCE
)
bobui_commandline_option(android-style-assets TYPE boolean)
bobui_commandline_option(appstore-compliant TYPE boolean)
bobui_commandline_option(avx TYPE boolean)
bobui_commandline_option(avx2 TYPE boolean)
bobui_commandline_option(avx512 TYPE boolean NAME avx512f)
bobui_commandline_option(c++std TYPE cxxstd)
bobui_commandline_option(unity-build TYPE boolean NAME unity_build CMAKE_VARIABLE BOBUI_UNITY_BUILD)
bobui_commandline_option(unity-build-batch-size
    TYPE string
    NAME unity_build_batch_size
    CMAKE_VARIABLE BOBUI_UNITY_BUILD_BATCH_SIZE
)
bobui_commandline_option(ccache TYPE boolean NAME ccache CMAKE_VARIABLE BOBUI_USE_CCACHE)
bobui_commandline_option(commercial TYPE void)
bobui_commandline_option(confirm-license TYPE void)
bobui_commandline_option(dbus TYPE optionalString VALUES no yes linked runtime)
bobui_commandline_option(dbus-linked TYPE void NAME dbus VALUE linked)
bobui_commandline_option(dbus-runtime TYPE void NAME dbus VALUE runtime)
bobui_commandline_option(debug TYPE void)
bobui_commandline_option(debug-and-release TYPE boolean NAME debug_and_release)
bobui_commandline_option(device TYPE string)
bobui_commandline_option(device-option TYPE addString CMAKE_VARIABLE BOBUI_QMAKE_DEVICE_OPTIONS)
bobui_commandline_option(f16c TYPE boolean)
bobui_commandline_option(force-asserts TYPE boolean NAME force_asserts)
bobui_commandline_option(force-debug-info TYPE boolean NAME force_debug_info)
bobui_commandline_option(force-pkg-config TYPE void NAME pkg-config)
bobui_commandline_option(force-bundled-libs TYPE boolean)
bobui_commandline_option(force-system-libs TYPE boolean)
bobui_commandline_option(framework TYPE boolean)
bobui_commandline_option(gc-binaries TYPE boolean NAME gc_binaries)
bobui_commandline_option(gdb-index TYPE boolean NAME enable_gdb_index)
bobui_commandline_option(gcov TYPE boolean)
bobui_commandline_option(gnumake TYPE boolean NAME GNUmake)
bobui_commandline_option(gui TYPE boolean)
bobui_commandline_option(incredibuild-xge TYPE boolean NAME incredibuild_xge)
bobui_commandline_option(libudev TYPE boolean)
bobui_commandline_option(openssl TYPE optionalString VALUES no yes linked runtime)
bobui_commandline_option(openssl-linked TYPE void NAME openssl VALUE linked)
bobui_commandline_option(openssl-runtime TYPE void NAME openssl VALUE runtime)
bobui_commandline_option(linker TYPE optionalString VALUES bfd gold lld mold)
bobui_commandline_option(ltcg TYPE boolean)
bobui_commandline_option(intelcet TYPE boolean)
bobui_commandline_option(glibc-fortify-source TYPE boolean NAME glibc_fortify_source)
bobui_commandline_option(trivial-auto-var-init-pattern TYPE boolean NAME trivial_auto_var_init_pattern)
bobui_commandline_option(stack-protector TYPE boolean NAME stack_protector)
bobui_commandline_option(stack-clash-protection TYPE boolean NAME stack_clash_protection)
bobui_commandline_option(libstdcpp-assertions TYPE boolean NAME libstdcpp_assertions)
bobui_commandline_option(libcpp-hardening TYPE boolean NAME libcpp_hardening)
bobui_commandline_option(relro-now-linker TYPE boolean NAME relro_now_linker)
set(allowed_build_parts examples tests benchmarks manual-tests minimal-static-tests doc-snippets)
bobui_commandline_option(make TYPE addString VALUES ${allowed_build_parts})
bobui_commandline_option(nomake TYPE addString VALUES ${allowed_build_parts})
bobui_commandline_option(install-examples-sources
    TYPE boolean
    CMAKE_VARIABLE BOBUI_INSTALL_EXAMPLES_SOURCES
)
bobui_commandline_option(mips_dsp TYPE boolean)
bobui_commandline_option(mips_dspr2 TYPE boolean)
bobui_commandline_option(opensource TYPE void NAME commercial VALUE no)
bobui_commandline_option(optimize-debug TYPE boolean NAME optimize_debug)
bobui_commandline_option(optimize-size TYPE boolean NAME optimize_size)
bobui_commandline_option(optimized-qmake TYPE boolean NAME release_tools)
bobui_commandline_option(optimized-tools TYPE boolean NAME optimized_tools)
bobui_commandline_option(pch TYPE boolean CMAKE_VARIABLE BUILD_WITH_PCH)
bobui_commandline_option(pkg-config TYPE boolean)
bobui_commandline_option(platform TYPE string CMAKE_VARIABLE BOBUI_QMAKE_TARGET_MKSPEC)
bobui_commandline_option(plugin-manifests TYPE boolean)
bobui_commandline_option(profile TYPE boolean)
bobui_commandline_option(qreal TYPE string CMAKE_VARIABLE BOBUI_COORD_TYPE)
bobui_commandline_option(bobuiinlinenamespace TYPE boolean CMAKE_VARIABLE BOBUI_INLINE_NAMESPACE)
bobui_commandline_option(bobuilibinfix
    TYPE string
    NAME bobui_libinfix
    CMAKE_VARIABLE BOBUI_LIBINFIX
)
bobui_commandline_option(bobuinamespace
    TYPE string
    NAME bobui_namespace
    CMAKE_VARIABLE BOBUI_NAMESPACE
)
bobui_commandline_option(reduce-exports TYPE boolean NAME reduce_exports)
bobui_commandline_option(reduce-relocations TYPE boolean NAME reduce_relocations)
bobui_commandline_option(release TYPE enum NAME debug MAPPING yes no no yes)
bobui_commandline_option(rpath TYPE boolean)
bobui_commandline_option(sanitize TYPE sanitize)
bobui_commandline_option(sdk TYPE string CMAKE_VARIABLE BOBUI_APPLE_SDK)
bobui_commandline_option(separate-debug-info TYPE boolean NAME separate_debug_info)
bobui_commandline_option(shared TYPE boolean)
bobui_commandline_option(silent TYPE void)
bobui_commandline_option(qdbus TYPE boolean NAME dbus)
bobui_commandline_option(sse2 TYPE boolean)
bobui_commandline_option(sse3 TYPE boolean)
bobui_commandline_option(sse4.1 TYPE boolean NAME sse4_1)
bobui_commandline_option(sse4.2 TYPE boolean NAME sse4_2)
bobui_commandline_option(ssse3 TYPE boolean)
bobui_commandline_option(static TYPE enum NAME shared MAPPING yes no no yes)
bobui_commandline_option(static-runtime TYPE boolean NAME static_runtime)
bobui_commandline_option(strip TYPE boolean)
bobui_commandline_option(sysroot TYPE string)
bobui_commandline_option(use-gold-linker TYPE boolean NAME use_gold_linker_alias)
bobui_commandline_option(warnings-are-errors
    TYPE boolean
    NAME warnings_are_errors
    CMAKE_VARIABLE WARNINGS_ARE_ERRORS
)
bobui_commandline_option(Werror TYPE boolean NAME warnings_are_errors)
bobui_commandline_option(widgets TYPE boolean)
bobui_commandline_option(xplatform TYPE string CMAKE_VARIABLE BOBUI_QMAKE_TARGET_MKSPEC)
bobui_commandline_option(zlib CONTROLS_FEATURE TYPE enum NAME system-zlib MAPPING system yes bobui no)
bobui_commandline_option(zstd TYPE boolean)
bobui_commandline_option(coverage TYPE optionalString VALUES gcov)
bobui_commandline_option(ffmpeg-dir TYPE path CMAKE_VARIABLE FFMPEG_DIR)
bobui_commandline_option(ffmpeg-deploy TYPE boolean CMAKE_VARIABLE BOBUI_DEPLOY_FFMPEG)
bobui_commandline_prefix(D defines)
bobui_commandline_prefix(F fpaths)
bobui_commandline_prefix(I includes)
bobui_commandline_prefix(L lpaths)
bobui_commandline_prefix(R rpaths)

function(bobui_commandline_cxxstd arg val nextok)
    if("${val}" STREQUAL "")
        bobuiConfGetNextCommandlineArg(val)
    endif()
    if("${val}" STREQUAL "" OR val MATCHES "^-.*")
        bobuiConfAddError("Missing argument to command line parameter '${arg}'.")
        return()
    endif()
    if(val MATCHES "(c\\+\\+)?(17|1z)")
        bobuiConfCommandlineDisableFeature(c++20)
        bobuiConfCommandlineDisableFeature(c++2b)
        bobuiConfCommandlineDisableFeature(c++2c)
    elseif(val MATCHES "(c\\+\\+)?(20|2a)")
        bobuiConfCommandlineEnableFeature(c++20)
        bobuiConfCommandlineDisableFeature(c++2b)
        bobuiConfCommandlineDisableFeature(c++2c)
    elseif(val MATCHES "(c\\+\\+)?(23|2b)")
        bobuiConfCommandlineEnableFeature(c++20)
        bobuiConfCommandlineEnableFeature(c++2b)
        bobuiConfCommandlineDisableFeature(c++2c)
    elseif(val MATCHES "(c\\+\\+)?(2c)")
        bobuiConfCommandlineEnableFeature(c++20)
        bobuiConfCommandlineEnableFeature(c++2b)
        bobuiConfCommandlineEnableFeature(c++2c)
    else()
        bobuiConfAddError("Invalid argument '${val}' to command line parameter '${arg}'")
    endif()
endfunction()

function(bobui_commandline_sanitize arg val nextok)
    if("${val}" STREQUAL "")
        bobuiConfGetNextCommandlineArg(val)
    endif()
    if("${val}" STREQUAL "" OR val MATCHES "^-.*")
        bobuiConfAddError("Missing argument to command line parameter '${arg}'.")
        return()
    endif()
    if(val STREQUAL "address")
        bobuiConfCommandlineEnableFeature(sanitize_address)
    elseif(val STREQUAL "thread")
        bobuiConfCommandlineEnableFeature(sanitize_thread)
    elseif(val STREQUAL "memory")
        bobuiConfCommandlineEnableFeature(sanitize_memory)
    elseif(val STREQUAL "fuzzer-no-link")
        bobuiConfCommandlineEnableFeature(sanitize_fuzzer_no_link)
    elseif(val STREQUAL "undefined")
        bobuiConfCommandlineEnableFeature(sanitize_undefined)
    else()
        bobuiConfAddError("Invalid argument '${val}' to command line parameter '${arg}'")
    endif()
endfunction()
