version = 1

[[annotations]]
path = ["tests/testdata/**", "test.lexgen"]
comment = "test data"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) The BobUI Company Ltd."
SPDX-License-Identifier = "LicenseRef-BobUI-Commercial OR GPL-3.0-only"

[[annotations]]
path = ["lexgen.lexgen", "css3-simplified.lexgen"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) The BobUI Company Ltd."
SPDX-License-Identifier = "LicenseRef-BobUI-Commercial OR GPL-3.0-only WITH BobUI-GPL-exception-1.0"
