/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p qibusproxyportal -c QIBusProxyPortal interfaces/org.freedesktop.IBus.Portal.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The BobUI Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QIBUSPROXYPORTAL_H
#define QIBUSPROXYPORTAL_H

#include <BobUICore/QObject>
#include <BobUICore/QByteArray>
#include <BobUICore/QList>
#include <BobUICore/QMap>
#include <BobUICore/QString>
#include <BobUICore/QStringList>
#include <BobUICore/QVariant>
#include <BobUIDBus/BobUIDBus>

/*
 * Proxy class for interface org.freedesktop.IBus.Portal
 */
class QIBusProxyPortal: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.IBus.Portal"; }

public:
    QIBusProxyPortal(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~QIBusProxyPortal();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QDBusObjectPath> CreateInputContext(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(name);
        return asyncCallWithArgumentList(QStringLiteral("CreateInputContext"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
