name: OmniUI WASM CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-wasm:
    name: Build on WebAssembly
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt for WASM
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
        host: 'linux'
        target: 'desktop'
        arch: 'wasm_32'
        modules: 'qtdeclarative qtwebsockets qt5compat'

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure CMake (WASM)
      run: |
        source $EMSDK/emsdk_env.sh
        cd OmniUI/examples/HelloOmni
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DQT_WASM=ON -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake ..

    - name: Build WASM Target
      run: |
        source $EMSDK/emsdk_env.sh
        cd OmniUI/examples/HelloOmni/build
        cmake --build . --parallel

    - name: Upload WASM Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HelloOmni-WASM
        path: OmniUI/examples/HelloOmni/build/*.html
        if-no-files-found: warn
